apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: test-psp
spec:
  allowPrivilegeEscalation: false
  allowedCapabilities:
  - SYS_RESOURCE
  defaultAllowPrivilegeEscalation: false
  fsGroup:
    rule: RunAsAny
  hostPorts:
  - max: 8000
    min: 6000
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny